# Generated by Django 3.2.9 on 2021-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('availability_in_percentage', models.IntegerField()),
                ('performance_in_percentage', models.IntegerField()),
                ('task', models.CharField(max_length=50)),
                ('work_activity', models.CharField(max_length=10)),
            ],
        ),
    ]
